name: manually build package using xcpkg

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true

      target-platform:
        description: input a target platform to be built for
        type: choice
        options:
          - MacOSX
          - AppleTVOS
          - AppleTVSimulator
          - WatchOS
          - WatchSimulator
          - iPhoneOS
          - iPhoneSimulator

      target-version:
        description: input a min target platform version to be supported
        required: true

      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - x86_64
          - arm64
          - arm64e
          - arm64_32
          - armv7k

      profile:
        description: choose a build profile
        type: choice
        options:
          - release
          - debug

      linkage:
        description: what library type would you like to link to the executable?
        type: choice
        options:
          - static
          - shared

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-vv'

jobs:

  build:

    runs-on: macos-26

    steps:
      - run: curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/xcpkg-0.30.0-macos-15.0-arm64.release.tar.xz
      - run: /usr/bin/bsdtar xf xcpkg-0.30.0-macos-15.0-arm64.release.tar.xz --strip-components=1

      - run: bin/xcpkg about
      - run: bin/xcpkg sysinfo
      - run: bin/xcpkg update
      - run: bin/xcpkg install ${{ github.event.inputs.target-platform }}-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} --profile=${{ github.event.inputs.profile }} ${{ github.event.inputs.log-level }}
      - run: bin/xcpkg bundle  ${{ github.event.inputs.target-platform }}-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} .tar.xz -v

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}---${{ github.event.inputs.target-platform }}-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}.tar.xz
          path: ./*.tar.xz
