name: manually build package using xcpkg

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true

      target-platform:
        description: input a target platform to be built for
        type: choice
        options:
          - MacOSX
          - AppleTVOS
          - AppleTVSimulator
          - WatchOS
          - WatchSimulator
          - iPhoneOS
          - iPhoneSimulator

      target-version:
        description: input a min target platform version to be supported
        required: true

      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - x86_64
          - arm64
          - arm64e
          - arm64_32
          - armv7k

      profile:
        description: choose a build profile
        type: choice
        options:
          - release
          - debug

      linkage:
        description: what library type would you like to link to the executable?
        type: choice
        options:
          - static
          - shared

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-vv'

      bundle-type:
        description: choose a bundle type
        type: choice
        options:
          - .tar.xz
          - .tar.lz
          - .tar.gz
          - .tar.bz2
          - .zip

      runner:
        description: choose a GitHub Actions runner
        type: choice
        options:
          - macos-26
          - macos-15
          - macos-14

      publish:
        description: whether to publish as GitHub release
        type: boolean
        default: false


jobs:

  build:

    runs-on: ${{ github.event.inputs.runner }}

    steps:
      - run: curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/xcpkg-0.30.0-macos-15.0-arm64.release.tar.xz
      - run: /usr/bin/bsdtar xf xcpkg-0.30.0-macos-15.0-arm64.release.tar.xz --strip-components=1
      - run: rm xcpkg-*.tar.xz

      - run: bin/xcpkg about
      - run: bin/xcpkg sysinfo
      - run: bin/xcpkg update
      - run: bin/xcpkg install ${{ github.event.inputs.target-platform }}-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} --profile=${{ github.event.inputs.profile }} ${{ github.event.inputs.log-level }}
      - run: bin/xcpkg bundle  ${{ github.event.inputs.target-platform }}-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} ${{ github.event.inputs.bundle-type }} -v

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.inputs.package-name }}---${{ github.event.inputs.target-platform }}-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}${{ github.event.inputs.bundle-type }}
          path: ./*${{ github.event.inputs.bundle-type }}


  publish:
    needs: build
    if: github.event.inputs.publish == 'true'

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls -a

      # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
      - run: git -c init.defaultBranch=master init
      - run: git remote add origin ${{ github.repositoryUrl }}

      - run: |
          FILENAME="$(ls ./*${{ github.event.inputs.bundle-type }})"

          gh release create "$FILENAME" "$FILENAME" --title "$FILENAME" --notes "$FILENAME"
